name: auto_clicker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  go_router: ^16.2.4
  webview_flutter: ^4.13.0
  favicon: ^1.1.2
  url_launcher: ^6.3.2
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.2
  path: ^1.9.1
  purchases_flutter: ^8.10.2
  purchases_ui_flutter: ^8.10.2
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: w400
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
    - family: w500
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
    - family: w600
      fonts:
        - asset: assets/fonts/Rubik-SemiBold.ttf
    - family: w700
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
